<a href="https://colab.research.google.com/github/kdrhanshn/Colab/blob/main/python_veri_manipilasyonu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("a")

a


##*Merhaba

In [ ]:
"A"

'A'

##Neden Numpy

In [ ]:
#bu bir alt başlıktır

In [ ]:
a = [1,2,3,4]
b = [2,3,4,5]
a
b

[2, 3, 4, 5]

In [ ]:
b

[2, 3, 4, 5]

In [ ]:
a

[1, 2, 3, 4]

In [ ]:
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0, len(a)):
  ab.append(a[i]*b[i])
  
  ab

In [ ]:
ab

[2, 6, 12, 20]

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])


In [ ]:
a * b

array([ 2,  6, 12, 20])

##NUMPY ARRAYİ OLUŞTURMAK

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [ ]:
np.array([3.14,4,2,13], dtype = "int") ##numpyın sabit tip baskısı vardır tek tip veri tutar.

array([ 3,  4,  2, 13])

In [ ]:
#sıfırdan array oluşturmak

In [ ]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.random.normal(10, 4, (3,4)) #ort-ssapma matris boyutu tek boyutlu vektör iki boyutlu matris

array([[ 9.66032767, 10.56139334,  5.39854703,  9.95906839],
       [ 9.54452077,  2.38181819,  8.55227903, 14.52868321],
       [ 7.46407029, 15.8317689 , 12.52450127,  9.73579645]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[5, 7, 2],
       [8, 7, 2],
       [0, 0, 0]])

In [ ]:
#

## #**özellikleri** *italicized text*
# ndim: boyut sayısı
#shape: boyut bilgisi
#size : toplam eleman sayısı
#dtype array veri tipi

In [ ]:
import numpy as np

In [ ]:
np.random.randint(10, size =10)

array([8, 7, 9, 9, 6, 9, 9, 7, 7, 3])

In [ ]:
a = np.random.randint(10, size=10)

In [ ]:
a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [ ]:
a.size


10

In [ ]:
a.shape


(10,)

In [ ]:
a.ndim


1

In [ ]:
b = np.random.randint(10, size=(3,5))

In [ ]:
b

array([[8, 1, 0, 3, 1],
       [5, 8, 1, 4, 0],
       [4, 9, 9, 0, 1]])

In [ ]:
b.shape

(3, 5)

In [ ]:
b.size


15

In [ ]:
b.dtype

dtype('int64')

#Yeniden Şekillendirme(reshaping)

In [ ]:
import numpy as np

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.arange(1,10)


In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.ndim

1

In [ ]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
b = a.reshape(1,9)

In [ ]:
b.ndim

2

#Birleştirme(Concatenation)

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y= np.array([4,5,6])

In [ ]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
z = np.array([7,8,9])

In [ ]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
##İki boyut

In [ ]:
a = np.array([[1,2,3], 
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a,a], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [ ]:
x = np.array([1,2,3,99,99,3,2,1])

In [ ]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [ ]:
a,b,c = np.split(x, [3,5])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([99, 99])

In [ ]:
c

array([3, 2, 1])

In [ ]:
# İki boyutlu ayırma

In [ ]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
ust, alt = np.vsplit(m,[2])

In [ ]:
ust 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
sag,sol = np.hsplit(m,[2])

In [ ]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#Array Sıralama (Sorting)

In [ ]:
import numpy as np

In [ ]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [ ]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
v

array([2, 1, 4, 3, 5])

In [ ]:
#İki boyutlu array sıralama

In [ ]:
m = np.random.normal(20,5, (3,3))

In [ ]:
m

array([[21.87901138, 18.23974269, 20.19567436],
       [15.27325826, 21.34161138, 17.45484413],
       [14.14913131, 25.0645181 , 23.03530462]])

In [ ]:
np.sort (m, axis=1)

array([[18.23974269, 20.19567436, 21.87901138],
       [15.27325826, 17.45484413, 21.34161138],
       [14.14913131, 23.03530462, 25.0645181 ]])

In [ ]:
np.sort (m, axis=0)

array([[14.14913131, 18.23974269, 17.45484413],
       [15.27325826, 21.34161138, 20.19567436],
       [21.87901138, 25.0645181 , 23.03530462]])

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(10, size= 10)

In [ ]:
a

array([9, 9, 6, 1, 7, 3, 1, 2, 1, 4])

In [ ]:
a[0]

9

In [ ]:
a[-1]

4

In [ ]:
a[0] = 100

In [ ]:
a


array([100,   9,   6,   1,   7,   3,   1,   2,   1,   4])

In [ ]:
m = a = np.random.randint(10, size= (3,5))
m

array([[6, 5, 7, 0, 9],
       [5, 3, 7, 9, 6],
       [7, 4, 4, 1, 1]])

In [ ]:
m[0,0]

6

In [ ]:
m[1,1]

3

In [ ]:
m[1,1] = 31
m

array([[ 6,  5,  7,  0,  9],
       [ 5, 31,  7,  9,  6],
       [ 7,  4,  4,  1,  1]])

Slicing ile Elemenlara Erişmek (array alt Kümesine Erişmke)

In [ ]:
import numpy as np
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
a[0:3]

array([20, 21, 22])

In [ ]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [ ]:
a[:3]

array([20, 21, 22])

In [ ]:
a[1::2]

array([21, 23, 25, 27, 29])

In [ ]:
a[0::2]

array([20, 22, 24, 26, 28])

In [ ]:
a[2::2]

array([22, 24, 26, 28])

In [ ]:
a[0::3]

array([20, 23, 26, 29])

In [ ]:
# iki boyutlu slice islemleri

In [ ]:
m = np.random.randint(10, size = (5,5))
m

array([[7, 7, 0, 1, 2],
       [3, 9, 9, 4, 7],
       [8, 4, 5, 0, 5],
       [1, 3, 7, 1, 1],
       [9, 7, 0, 7, 4]])

In [ ]:
m[:,0]

array([7, 3, 8, 1, 9])

In [ ]:
m[:,1]

array([7, 9, 4, 3, 7])

In [ ]:
m[:,4]

array([2, 7, 5, 1, 4])

In [ ]:
m[0,:]

array([7, 7, 0, 1, 2])

In [ ]:
m[1,:]

array([3, 9, 9, 4, 7])

In [ ]:
m[0:2, 0:3]

array([[7, 7, 0],
       [3, 9, 9]])

In [ ]:
m [::,:2]

array([[7, 7],
       [3, 9],
       [8, 4],
       [1, 3],
       [9, 7]])

In [ ]:
m[1:3 , 0:2]

array([[3, 9],
       [8, 4]])

ALT KÜME ÜZERİNDE İŞLEM YAPMAK 

In [ ]:
import numpy as np 
a = np.random.randint(10, size = (5, 5))
a

array([[2, 4, 9, 6, 9],
       [8, 5, 6, 1, 2],
       [4, 5, 7, 3, 4],
       [6, 5, 7, 6, 4],
       [6, 3, 8, 5, 4]])

In [ ]:
alt_A = a[0:3 , 0:2]
alt_A

array([[2, 4],
       [8, 5],
       [4, 5]])

In [ ]:
alt_A[0,0] = 9999
alt_A[1,1] = 888
alt_A

array([[9999,    4],
       [   8,  888],
       [   4,    5]])

In [ ]:
a

array([[9999,    4,    9,    6,    9],
       [   8,  888,    6,    1,    2],
       [   4,    5,    7,    3,    4],
       [   6,    5,    7,    6,    4],
       [   6,    3,    8,    5,    4]])

In [ ]:
m = np.random.randint(10, size = (5, 5))
m

array([[3, 4, 0, 8, 9],
       [4, 1, 0, 6, 9],
       [2, 5, 2, 3, 0],
       [4, 9, 6, 6, 2],
       [6, 5, 5, 3, 1]])

In [ ]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[3, 4],
       [4, 1],
       [2, 5]])

In [ ]:
alt_b[0,0] =999


In [ ]:
alt_b

array([[999,   4],
       [  4,   1],
       [  2,   5]])

In [ ]:
m

array([[3, 4, 0, 8, 9],
       [4, 1, 0, 6, 9],
       [2, 5, 2, 3, 0],
       [4, 9, 6, 6, 2],
       [6, 5, 5, 3, 1]])

FANCY Index İle Elemanlara Erişmek

In [ ]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
v[1]

3

In [ ]:
v[3]

9

In [ ]:
v[5]

15

In [ ]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [ ]:
al_getir = [1,3,5]

In [ ]:
v[al_getir]

array([ 3,  9, 15])

In [ ]:
##İKİ BOYUTTA FANCY

In [ ]:
m= np.arange(9).reshape((3,3))

In [ ]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
satir = np.array([0,1])
sutun = np.array([1,2])
m[satir,sutun]

array([1, 5])

In [ ]:
#basit index ile fancy

In [ ]:
m[0,[1,2]]

array([1, 2])

In [ ]:
#slice

In [ ]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

#KOŞULLU ELEMAN İŞLEMLERİ

In [ ]:
import numpy as np

In [ ]:
v = np.array([1,2,3,4,5])

In [ ]:
v<3

array([ True,  True, False, False, False])

In [ ]:
v[v<3]

array([1, 2])

In [ ]:
v[v>3]

array([4, 5])

In [ ]:
v[v<=3]

array([1, 2, 3])

In [ ]:
v[v>=3]

array([3, 4, 5])

In [ ]:
v[v==3]

array([3])

In [ ]:
v* 2

array([ 2,  4,  6,  8, 10])

In [ ]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

#MATEMATİKSEL İŞLEMLER

In [ ]:
import numpy as np

In [ ]:
v = np.array([1,2,3,4,5])


In [ ]:
v-1

array([0, 1, 2, 3, 4])

In [ ]:
v*5

array([ 5, 10, 15, 20, 25])

In [ ]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#ufunc

In [ ]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

#NUMPY İLE İKİ BİLİNMEYENLİ DENKLEM

In [ ]:
import numpy as np

In [ ]:
a = np.array([[5,1] , [1,3]])
b = np.array([12,10])
a

array([[5, 1],
       [1, 3]])

In [ ]:
b

array([12, 10])

In [ ]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])